name: MongoTransit development CI

on: [
    workflow_dispatch,
    pull_request
]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Unit tests
      run: dotnet test --no-restore MongoTransit.UnitTests
    - name: Create MongoDB Sharded Cluster
      run: (cd docker-compose && sh init-cluster.sh)
    - name: Integration tests
      run: dotnet test --no-restore MongoTransit.IntegrationTests