name: MongoTransit new version release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  DOTNET_VER: 7.0.x

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VER }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore

  unit-tests:
    
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VER }}
      - name: Unit tests
        run: dotnet test MongoTransit.UnitTests

  integration-tests:
    
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VER }}
      - name: Create MongoDB Sharded Cluster
        run: (cd docker-compose && sh init-cluster.sh)
      - name: Integration tests
        run: dotnet test MongoTransit.IntegrationTests  

  publish-release:

    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests]

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VER }}

    - name: Bump version and push tag
      id: bump-version
      uses: anothrNick/github-tag-action@1.61.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false

    - name: Publish Linux x64
      run: dotnet publish MongoTransit/MongoTransit.csproj -c Release -r linux-x64 -p:Version=${{ steps.bump-version.outputs.new_tag }} -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true --self-contained -o Releases/linux-x64
      
    - name: Print Linux x64 version
      run: ./Releases/linux-x64/MongoTransit --version
    
    - name: Upload MongoTransit executable into build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mongotransit-linux-x64
        path: Releases/linux-x64/MongoTransit
    
    - name: Create release
      if: github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.bump-version.outputs.new_tag }}
        files: Releases/linux-x64/MongoTransit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
