name: .NET

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Unit tests
      run: dotnet test --no-restore MongoTransit.UnitTests
    - name: Start integration MongoDB
      run: (cd mongo-transit-sharded-cluster && sh init.sh)
