name: MongoTransit new version release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  DOTNET_VER: 6.0.x

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VER }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore

  unit-tests:
    
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VER }}
      - name: Unit tests
        run: dotnet test MongoTransit.UnitTests

  integration-tests:
    
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VER }}
      - name: Create MongoDB Sharded Cluster
        run: (cd docker-compose && sh init-cluster.sh)
      - name: Integration tests
        run: dotnet test MongoTransit.IntegrationTests  

  publish-release:

    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests]

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VER }}
    
    - name: Publish Linux x64
      run: dotnet publish MongoTransit/MongoTransit.csproj --configuration Release --runtime linux-x64 -p:PublishSingleFile=true --self-contained -o Releases/linux-x64
    
    - name: Upload MongoTransit executable into build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mongotransit-linux-x64
        path: Releases/linux-x64/MongoTransit
    
    - name: Bump version and push tag
      if: github.ref == 'refs/heads/master'
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
    
    - name: Create release
      if: github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.bump.outputs.new_tag }}
        files: Releases/linux-x64/MongoTransit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
