name: .NET

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --runtime linux-x64 --no-restore
    - name: Unit tests
      run: dotnet test --no-restore --verbosity normal
    - name: Publish Linux x64
      run: dotnet publish --configuration Release --runtime linux-x64 -p:PublishSingleFile=true --no-restore
